### ISSUE TITLE
Sound files for thunder?

### ISSUE THREAD

**Issue by danesparza** [BrianEnigma/halloween-thunderfx#1]
Thanks for this!  Maybe I missed it in the source code, but I don't see any sound files.  Do you have some samples for use in this project?

**Comment by BrianEnigma** [comment]
The sounds I have are likely copyrighted. You should be able to search around the internet for some nice ones. As I recall, I had to convert some mp3 files into wav using Audacity. You then name the first one 1.wav. If you have more than one, you can name them up to 9.wav.
